package fr.formation.inti.Entities;
// Generated 26 avr. 2019 11:17:57 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Annonces generated by hbm2java
 */
@Entity
@Table(name = "annonces", catalog = "projet")
public class Annonces implements java.io.Serializable {

	private Integer idAnnonces;
	private Utilisateurs utilisateurs;
	private String description;
	private String photo;
	private int prix;
	private Date date;
	private String adresse;
	private String titre;
	private AnnoncesHasMotsclefs annoncesHasMotsclefs;

	public Annonces() {
	}

	public Annonces(Utilisateurs utilisateurs, String description, int prix, Date date, String adresse, String titre) {
		this.utilisateurs = utilisateurs;
		this.description = description;
		this.prix = prix;
		this.date = date;
		this.adresse = adresse;
		this.titre = titre;
	}

	public Annonces(Utilisateurs utilisateurs, String description, String photo, int prix, Date date, String adresse,
			String titre, AnnoncesHasMotsclefs annoncesHasMotsclefs) {
		this.utilisateurs = utilisateurs;
		this.description = description;
		this.photo = photo;
		this.prix = prix;
		this.date = date;
		this.adresse = adresse;
		this.titre = titre;
		this.annoncesHasMotsclefs = annoncesHasMotsclefs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAnnonces", unique = true, nullable = false)
	public Integer getIdAnnonces() {
		return this.idAnnonces;
	}

	public void setIdAnnonces(Integer idAnnonces) {
		this.idAnnonces = idAnnonces;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "utilisateurs_idUtilisateurs", nullable = false)
	public Utilisateurs getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Utilisateurs utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	@Column(name = "Description", nullable = false, length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Photo", length = 45)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "Prix", nullable = false)
	public int getPrix() {
		return this.prix;
	}

	public void setPrix(int prix) {
		this.prix = prix;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Adresse", nullable = false, length = 45)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "Titre", nullable = false, length = 45)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "annonces")
	public AnnoncesHasMotsclefs getAnnoncesHasMotsclefs() {
		return this.annoncesHasMotsclefs;
	}

	public void setAnnoncesHasMotsclefs(AnnoncesHasMotsclefs annoncesHasMotsclefs) {
		this.annoncesHasMotsclefs = annoncesHasMotsclefs;
	}

}
