package fr.formation.inti.entities;
// Generated 26 avr. 2019 11:17:57 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * MotsclefsHasAlerte generated by hbm2java
 */
@Entity
@Table(name = "motsclefs_has_alerte", catalog = "projet")
public class MotsclefsHasAlerte implements java.io.Serializable {

	private int motsclefsIdMotClef;
	private Alerte alerte;
	private MotsClefs motsclefs;

	public MotsclefsHasAlerte() {
	}

	public MotsclefsHasAlerte(Alerte alerte, MotsClefs motsclefs) {
		this.alerte = alerte;
		this.motsclefs = motsclefs;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "motsclefs"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "motsclefs_idMotClef", unique = true, nullable = false)
	public int getMotsclefsIdMotClef() {
		return this.motsclefsIdMotClef;
	}

	public void setMotsclefsIdMotClef(int motsclefsIdMotClef) {
		this.motsclefsIdMotClef = motsclefsIdMotClef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Alerte_idAlerte", nullable = false)
	public Alerte getAlerte() {
		return this.alerte;
	}

	public void setAlerte(Alerte alerte) {
		this.alerte = alerte;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public MotsClefs getMotsclefs() {
		return this.motsclefs;
	}

	public void setMotsclefs(MotsClefs motsclefs) {
		this.motsclefs = motsclefs;
	}

}
